/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hotel;

import javax.swing.SwingUtilities;

import com.formdev.flatlaf.themes.FlatMacLightLaf;

import org.hotel.controller.BookingsController;
import org.hotel.controller.DashboardController;
import org.hotel.controller.RoomsController;
import org.hotel.db.Database;
import org.hotel.view.MainFrame;

public class Main {

  public static void main(String[] args) {
    FlatMacLightLaf.setup();
    Database.initializeDatabase();

    SwingUtilities.invokeLater(() -> {
      MainFrame mainFrame = new MainFrame();
      new RoomsController(mainFrame);
      new BookingsController(mainFrame);
      new DashboardController(mainFrame);

      mainFrame.showView("Dashboard");
      mainFrame.getDashboardBtn().doClick();
      ;
    });
  }
}
