/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hotel;

import com.formdev.flatlaf.themes.FlatMacLightLaf;

import org.hotel.db.Database;
import org.hotel.view.LoginFrame;

public class Main {

  public static void main(String[] args) {
    FlatMacLightLaf.setup();
    Database.initializeDatabase();

    // SwingUtilities.invokeLater(() -> {
    // MainFrame mainFrame = new MainFrame();
    // new RoomsController(mainFrame);
    // new BookingsController(mainFrame);
    // new DashboardController(mainFrame);
    // new UserController(mainFrame);
    //
    // mainFrame.showView("Dashboard");
    // mainFrame.getDashboardBtn().doClick();
    // ;
    // });
    new LoginFrame();
  }
}
